### PR TITLE
Don't install the additional Open-Source Modelica Libraries by default

### PR DESCRIPTION
**Pull request by adeas31**

### CODE REVIEW

**Comment by adeas31** [comment]
@casella should I push this in?
This basically makes sure that the additional libraries (around 1.5 GB) are not installed by default unless the user wants to.

**Comment by adrpo** [comment]
@casella I don't remember if you want the Windows installer to not install any additional libraries by default. Can you confirm that?

**Comment by adrpo** [comment]
Geez, I didn't see @adeas31 already asked @casella about this stuff, sorry about that!

**Review by adrpo — APPROVED** [review]
OK with me, pending the OK from Francesco.

**Comment by casella** [comment]
I'm not sure at this point. It's a balance between letting users experiments with existing libraries (the more, the better) on one side, and on the other side making sure they are not unnecessarily bogged down by tons of mostly useless stuff, VisualStudio-style, or worse, by tons of stuff that actually doesn't work at all.

After yesterday's trimming session with @adrpo and @sjoelund, maybe installing everything by default is not as bad as it used to be. Possibly around 400-600 MB now and 30-40.000 files, which is more resonable, and most of it working.

Let me try to install 1.16.0-dev.03 and see how it looks like. We can decide to merge this PR later, if needed.

**Comment by adeas31** [comment]
I guess this PR is now kind of obsolete after the trimming of libraries. Shall I just close this PR then?

**Comment by adrpo** [comment]
Seems the libs we install now on Windows are ~1.2GB. 
```
# make -f Makefile.omdev.mingw omlibrary-all
# du -sh build/lib/omlibrary/
1.2G    build/lib/omlibrary/
```

**Comment by casella** [comment]
Aren't we planning to only install the core libraries in 1.17.0, and suggest using the package manager for all other ones?

**Comment by adeas31** [comment]
Yes the package manager for sure makes this PR invalid. But 1.17.0 is already upon us so there will be at least no GUI support for it.

**Comment by adeas31** [comment]
Closing this PR as we only install core libraries now.

**Pull request closed without merging**
