### PR TITLE
Install MSL version 4.0.0 as default

### PR DESCRIPTION
**Pull request by adeas31**

### CODE REVIEW

**Comment by adrpo** [comment]
No. Not instead of 3.2.3, both of them so is easy to switch.

**Comment by adeas31** [comment]
Both of them will be installed but 3.2.3 will be in the list of optional libraries. It will be installed by default but user can uncheck it.

This is what we have right now in the installer. With this PR it will be switched,
image
image

**Review by adrpo — APPROVED** [review]
Then is fine!

**Comment by casella** [comment]
Wait, I am not sure that making MSL 3.2.3 "optional" in 1.17.0 is a good idea. 

Most people are still using MSL 3.2.3, which is still supported by the MA in maintenance mode, and we are not yet providing conversion scripts to migrate to 4.0.0. I'll continue the discussion in [#6247](https://trac.openmodelica.org/OpenModelica/ticket/6274)

**Pull request merged**
